Project Cophr {
  database_type: 'PostgreSQL'
  Note: '''
    # Cophr Database
  '''
}

Table users {
  id int [pk, increment]
  email varchar(256) [unique, not null, note: "用作登入等用途之信箱"]
  name varchar [not null, note: "顯示名"]
  account varchar [unique, not null, note: "帳號"]
  password varchar [null, note: "密碼"]
  created_at timestamp [not null, default: `now()`]
  note: "使用者基本資料"
}

Table places {
  id int [pk, increment]
  title varchar [not null, note: "地點名稱"]
  address text [not null, note: "活動地址"]
  note: "活動地點"
}





// OAuth Integration
Table auth_providers {
  id int [pk, increment]
  title varchar [not null]
  client_id varchar [not null, note: "oauth client id"]
  client_secret varchar [not null, note: "oauth client secret"]
  scope varchar [null, note: "oauth scope"]
  redirect_uri varchar [not null, note: "oauth redirect uri"]
  can_login boolean [not null, note: "是否可以透過這個登入"]
  note: "驗證服務提供者"
}

Table oauth_integrations {
  auth_provider int [not null, ref: > auth_providers.id]
  user int [not null, ref: > users.id]
  external_id varchar [not null, note: "3rd party service id"]
  access_token varchar [not null, note: "user's access token"]
  refresh_token varchar [not null, note: "user's refresh token"]
  expire_at timestamp [not null, note: "expire time of token"]

  indexes {
    (auth_provider, user)[unique]
  }
  note: "帳號整合"
}





// Event
Table events {
  id int [pk, increment]
  title varchar [not null, note: "活動標題"]
  type varchar [note: "活動類型, 說明這個活動與 Cosplay 的關係，可能值見 event_type"]
  description text [null, note: "活動說明, markdown"]
  link text [not null, note: "活動網站"]
  note: "Cosplay 場次"
}

enum event_type {
  additional [note: "附帶 Cosplay 的活動"]
  specialized [note: "專門給 Cosplay 的活動"]
}

Ref event_images: events.id <> images.id

Table event_days {
  id int [pk, increment]
  event int [not null, ref: > events.id]
  description text [null, note: "補充說明, markdown"]
  event_date date [not null, note: "活動日期"]
  start_time time [not null, note: "活動開始時間"]
  end_time time [not null, note: "活動結束時間"]
  place int [not null, ref: > places.id, note: "活動地點"]
}

Table event_cosplayer_costume {
  id int [pk, increment]
  event_day int [not null, ref: > event_days.id]
  user int [not null, ref: > users.id]
  character int [not null, ref: > characters.id]
  costume int [not null, ref: > costumes.id]
  comment varchar [null, note: "補充說明"]

  indexes {
     (event_day, user, character, costume) [unique]
  }
  note: "場次中會出現的 Cosplayer 跟其時裝"
}

Table event_photographers {
  id int [pk, increment]
  event_day int [not null, ref: > event_days.id]
  user int [not null, ref: > users.id]
  comment varchar [null, note: "補充說明"]

  indexes {
     (user, event_day) [unique]
  }
  note: "場次中會出現的攝影師"
}





// Cosplay related 
Table works {
  id int [pk, increment]
  title varchar [not null, note: "作品標題"]
  description text [null, note: "作品簡介, markdown"]
  link text [null, note: "相關連結"]
  note: "Cosplay 的相關作品"
}

Ref work_images: works.id <> images.id
Ref character_work: works.id <> characters.id

Table characters {
  id int [pk, increment]
  title varchar [not null, note: "角色名"]
  description text [null, note: "角色簡介, markdown"]
  link text [null, note: "相關連結"]
  note: "Cosplay 的角色"
}

Ref character_images: characters.id <> images.id
Ref costume_character: characters.id <> costumes.id

Table costumes {
  id int [pk, increment]
  title varchar [not null, note: "時裝標題"]
  description text [null, note: "時裝簡介, markdown"]
  link text [null, note: "相關連結"]
  note: "時裝"
}

Ref costume_images: costumes.id <> images.id





// Photograph (use flickr)
Table albums {
  id int [pk, increment]
  flickr_id varchar [unique, not null, note: "Flickr 上的 album ID"]
  event_day int [not null, ref: > event_days.id]

  note: "Flickr 相簿，可以收錄上傳的照片"
}

Table galleries {
  id int [pk, increment]
  flickr_id varchar [unique, not null, note: "Flickr 上的 gallery ID"]
  event_day int [not null, ref: > event_days.id]

  note: "Flickr 展覽館，可以收錄包括非該帳號上傳的照片"
}

Table photos {
  id int [pk, increment]
  flickr_id varchar [unique, not null, note: "Flickr 上的 photo ID"]
  user int [not null, ref: > users.id, note: "攝影師/上傳者"]
  note: "場次中拍到的照片"
}

Ref photo_event: photos.id <> event_days.id
Ref photo_cosplayers: photos.id <> event_cosplayer_costume.id
Ref photo_likes: photos.id <> users.id

Table photo_cosplayer_recommendations {
  id int [pk, increment]
  photo int [not null, ref: > photos.id, note: "在哪張照片被 tag"]
  user int [not null, ref: > users.id, note: "被 Tag 的使用者"]
  verified boolean [null, note: "是否是本人，null 為尚未驗證"]

  indexes {
     (photo, user) [unique]
  }
  note: "一般使用者在照片上標記人（建議誰可能是相中人）"
}

Ref photo_cosplayer_recommended_by: photo_cosplayer_recommendations.id <> users.id





// Images (use imgur)
Table images {
  id int [pk, increment]
  uploader int [not null, ref: > users.id, note: "上傳者"]
  imgur_id varchar [not null, note: "Imgur 圖片 ID"]
  note: "圖片，用於作品、角色的敘述圖（非照片）"
}
